# Generated by Django 3.0.6 on 2020-08-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('name', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
